# ************************************************************************
#  @author:     Andreas Kaeberlein
#  @copyright:  Copyright 2021
#  @credits:    AKAE
#
#  @license:    GPLv3
#  @maintainer: Andreas Kaeberlein
#  @email:      andreas.kaeberlein@web.de
#
#  @file:       01_unittest.yml
#  @date:       2019-12-28
#
#  @brief:      runs test and deploy
#
# ************************************************************************


name: Unittest

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.x']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
          architecture: 'x64'   # optional x64 or x86. Defaults to x64 if not specified
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./.github/workflows/requirements.txt
      - name: Test sh641_drv.py
        run: |
          python ./test/unit/sh_641_drv/sh641_drv_unittest.py
      - name: Test simChamber.py
        run: |
          python ./test/unit/sim/simChamber_unittest.py
      - name: Test waves.py
        run: |
          python ./test/unit/waves/waves_unittest.py
      - name: Test ATWG.py
        run: |
          python ./test/unit/atwg/atwg_unittest.py
